name: Deploy to EKS 
on:
  push:
    paths:
      - 'k8s/**' 
    
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: aws/setup-kubectl@v3 
      with: 
        kubectl-version: '1.26.0' 
     - name: Configure AWS Credentials 
       uses: aws-actions/configure-aws-credentials@v2
       with:
         role-to-assume: arn:aws:iam::539935451710:role/ecr 
         aws-region: us-east-1 
      - name: Apply Kubernetes Manifests 
        run: kubectl apply -f k8s/
